import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
<<<<<<< HEAD
  weight: '100 900'
=======
  weight: '100 900',
>>>>>>> 9f6d897 (feat: update README with project details)
})
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
<<<<<<< HEAD
  weight: '100 900'
=======
  weight: '100 900',
>>>>>>> 9f6d897 (feat: update README with project details)
})

export const metadata: Metadata = {
  title: 'Create Next App',
<<<<<<< HEAD
  description: 'Generated by create next app'
=======
  description: 'Generated by create next app',
>>>>>>> 9f6d897 (feat: update README with project details)
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  )
}
